# Let s6
# Let s6 = a5s5 +· · ·+a1s1 represent a linear feedback shift register (LFSR) with coefficients
# a1a2a3a4a5 = 11001 and initial value s1s2s3s4s5 = 01011. Compute the next 5 bits
# generated by this LFSR

# LFSR
# add all the bits where there is a 1 in the coefficients
# mod 2 the sum to get the new bit

# xx  x
# 01011
#  10110
#   01101
#    11010
#     10100
#      01001

coefficients = [1, 1, 0, 0, 1]  # a1, a2, a3, a4, a5
initial_value = [0, 1, 0, 1, 1]

bits = initial_value.copy()
n = 5
for i in range(n):
    new_bit = (
        bits[0+i] * coefficients[0]
        + bits[1+i] * coefficients[1]
        + bits[2+i] * coefficients[2]
        + bits[3+i] * coefficients[3]
        + bits[4+i] * coefficients[4]
    )
    new_bit = new_bit % 2
    bits.append(new_bit)

print(bits)
print("Next 5 bits generated by the LFSR:", bits[5:10])
