# As discussed in class, a pseudorandom number generator (PRNG) is considered secure if
# it is computationally hard to distinguish its output from a uniformly random sequence.
# Explain why a PRNG based on a linear feedback shift register (LFSR) is not secure.


# A PRNG based on a linear feedback shift register is not secure because LFSRs are periodic and linear in nature.
# This means that the output sequence generated by an LFSR can be predicted if enough bits of the sequence are known.




# Pseudorandom Number Generators (PRNG)
# ▶ Uses a function for generation
# ▶ Uses a seed
# • Example:
# s_0 = seed
# s_{i+1} ≡ a * s_i + b (mod m)
# The rand() function in ANSI C:
# s_0 = 12345
# s_{i+1} ≡ 1103515245si + 12345 (mod 231)

# A PRNG which is unpredictable.
# ▶ Given a bunch of bits of the stream, it is computationally infeasible to compute the
# subsequent bits.
# ▶ More precisely: for some parameter n, given a polynomials (in n) number of consecutive
# bits of the stream, there is no polynomial time (in n) algorithm that can predict the next bit.



# Why an LFSR-Based PRNG Is Not Secure

# A secure PRNG must be unpredictable, meaning that given any polynomial number of consecutive output bits,
# there should be no polynomial-time algorithm that can predict the next bit with non-negligible advantage over random guessing.
# However, a PRNG based on a Linear Feedback Shift Register (LFSR) does not satisfy this requirement.

# An LFSR generates each new bit as a linear function (XOR) of a fixed number of previous bits.
# Because the recurrence relation is linear, the entire output stream satisfies a system of linear equations over GF(2).
# Given only O(n) consecutive output bits (where n is the size of the LFSR), an attacker can:

# Set up a system of linear equations that describes the feedback rule.
# Solve this system efficiently using Gaussian elimination in polynomial time.
# Recover the full internal state of the LFSR.
# Predict all future output bits exactly.

# This directly violates the unpredictability requirement:
# There exists a polynomial-time attack that, given polynomially many output bits,
# predicts the next bit with probability 1.

# Conclusion (Key Security Failure)
# Because:
# LFSRs are linear and periodic,
# Their internal state can be efficiently recovered, and
# Future bits become perfectly predictable,
# An LFSR-based PRNG is not secure under the standard cryptographic definition of unpredictability
#    and therefore is easily distinguishable from truly random output.

# A secure PRNG must be unpredictable, meaning that given a polynomial number of consecutive output bits, 
# no polynomial-time algorithm can predict the next bit with non-negligible advantage.
# A PRNG based on a linear feedback shift register (LFSR) is not secure because each
#     output bit is a linear function of previous bits.
# Given O(n) consecutive output bits, where n is the size of the LFSR,
# an attacker can efficiently set up and solve a system of linear equations to recover the internal state in polynomial time.
# Once the state is known, all future bits can be predicted exactly.
# This violates the unpredictability requirement, so LFSR-based PRNGs are not secure.