# Let g : Zp → Zp × Zp, be a PRNG defined by g(x) = (x^3 mod p, x^5 mod p). Is this PRNG secure? Explain.
# (You must investigate whether a sequence of pairs {g(x_i)} can be
# distinguished from a sequence {(a_i, b_i)} where a_i and b_i are uniformly random numbers.)

# A PRNG is considered secure if its output is indistinguishable from a uniformly random sequence.
# In this case, x^3 mod p and x^5 mod p have a mathematical relationship since both are derived from the same input x.
# This relationship does not hold in a truly random sequence, where each element is independent of the others.
# Meaning, that there exist pairs that cannot be generated by g(x) for any x in Zp.
# Therefore, it can be distinguished from a sequence of uniformly random pairs (a_i, b_i).
# Hence, this PRNG is not secure.





# This PRNG is not secure since it is periodic to the order of p,
# meaning if p is small enough it will not be secure since it will repeat quickly,
# however if p is too large then the output may never end up looping through the modulus operator
# which would make the output predictable

def g(x, p):
    return (pow(x, 3, p), pow(x, 5, p))

for i in range(25):
    print(g(i, 13))  # Example usage