# Suppose the public primes for the DSA signature scheme are
# p = 899009829279928687167847647253 and q = 5938170550372221380503.
# Which of the following is a public key beta for these parameters?

# A) 428025207316609689260868108104
# B) 511817553315794935894966990404
# C) 52741071529976599941769481354
# D) 430222494411980041758424435195

# DSA Signature Scheme
# Key Generation:
# 1. Generate a prime 2^1023 < p < 2^1024
# 2. Find a prime divisor q of p − 1 such that 2^159 < q < 2^160
# 3. Find an element α ∈ Z×_p of order q
# 4. Choose a random integer 0 < d < q
# 5. Compute β = α^d (mod p)

# Public parameters: (p, q, α)
# Public key: β
# Private key: d

# Signature generation:
# Input: x, d
# 1. Choose a random ephemeral key kE ∈ {0, 1, · · · , q − 1}
# 2. Compute r = (α^kE mod p) (mod q) and s = (h(x) + d · r)kE^{−1} (mod q)
# 3. Return r, s

# Signature verification:
# Input: x, r, s
# 1. Compute w = s^{−1} (mod q), u_1 = wh(x) (mod q), and u_2 = wr (mod q)
# 2. Compute t = (α^u_1 β^u_2 mod p) (mod q)
# 3. Return “valid” if t = r; otherwise return “invalid”

# Fermat's little theorem
# if p is a prime number, then for any integer a,
# a^p - a is a multiple of p.
# Equivalently, a^p ≡ a (mod p).
# If a is not divisible by p, then
# a^(p-1) ≡ 1 (mod p)

p = 899009829279928687167847647253
q = 5938170550372221380503
candidates = [
    428025207316609689260868108104,
    511817553315794935894966990404,
    52741071529976599941769481354,
    430222494411980041758424435195,
]


for beta in candidates:
    print("Testing beta =", beta)
    # beta is generated by β = α^d (mod p)
    # meaning it is in order q
    # beta = α^d (mod p)
    # b^q = (α^d)^q (mod p)
    # = α^(dq) (mod p)
    # = (a^q)^d (mod p)
    # = 1^d (mod p)
    # = 1
    # Therfore,
    # beta^q ≡ 1 (mod p)
    print(pow(beta, q, p) == 1)


